default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: zapdoc_dev

test:
  <<: *default
  database: zapdoc_test

production:
  <<: *default
  database: zapdoc_prod